apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: jit-data
  namespace: domino-field
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "<NUID_SECRET_ARN>"
        objectType: "secretsmanager"
        objectAlias: "nuid"
      - objectName: "<PING_SECRET_ARN>"
        objectType: "secretsmanager"
        objectAlias: "ping-client"