apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: jit-secrets
  namespace: domino-field
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "<SECRET_ARN>"
        objectType: "secretsmanager"
        objectAlias: "jit.json"
        jmesPath:
          - path: "cert"
            objectAlias: "certificate.cer"
