apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: domino-field
  labels:
    app: nginx
spec:
  serviceAccountName: jit
  volumes:
    - name: jit-secrets
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "jit-secrets"
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
      - name: jit-secrets
        mountPath: "/etc/config/jit/"