image:
  repository: quay.io/domino
  serverContainer: jit-server
  clientContainer: jit-client
  serverAppVersion: v1.0.0-release
  clientAppVersion: v1.0.0-release
  pullPolicy: Always

env:
  name: jit
  service: jit-svc
  iamrole: <JIT_SERVER_IAM_ROLE_ARN>
  # projects_attribute_name: some_attribute_name # For setting a custom keycloak-mapped attribute that ties to the groups/projects SAML assertion.
                                                 # Defaults to "fm_projects."

  namespace:
    platform: domino-platform
    compute: domino-compute
    field: domino-field 
  ping:
    url: "http://localhost" # Ping URL here
    client_id: "abcd"       # Ping clientID
  jit:
    url: "http://localhost" # Jit API Server URL
    username: "someuser"    # Jit Username
    # expiry_token_minimum: 30 # Minimum token expiry time, defaults to 10 sec.
  
# users: # This key is for limiting the use of the JIT service to specific users, for easier testing.
  # - someuser

testing: false
mock_server:
  jitMockContainer: jit-mock
  jitMockVersion: v1.0.0-release
  containerPort: 8080
  port: 80