apiVersion: v1
kind: ConfigMap
metadata:
  name: jit-config
  namespace: {{ .Values.env.namespace.field }}
data:
  jit.json: |-
    {
      "token_endpoint": "{{ .Values.env.ping.url }}",
      "client_id": "{{ .Values.env.ping.client_id }}",
      "jit_endpoint": "{{ .Values.env.jit.url }}"
      "r_username": "{{ .Values.env.jit.username }}",
      "minimum_token_validity_required_in_seconds": "{{ .Values.env.jit.expiry_token_minimum | default 3600 }}"
    }
  certificate.cer: |-
    {{ .Files.Get "certificate.crt" | nindent 4 | trim }}