{{ if .Values.testing }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "{{ .Values.env.name }}-mock-certificate"
  namespace: {{ .Values.env.namespace.field }}
spec:
  isCA: true
  secretName: "{{ .Values.env.name }}-mock-certs"
  dnsNames:
  - "{{ .Values.env.service }}-mock"
  - "{{ .Values.env.service }}-mock.{{ .Values.env.namespace.field }}"
  - "{{ .Values.env.service }}-mock.{{ .Values.env.namespace.field }}.svc"
  issuerRef:
    name: "selfsigned-{{ .Values.env.name }}-mock"
---

apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: "selfsigned-{{ .Values.env.name }}-mock"
spec:
  selfSigned: {}
{{ end }}  