{{ if .Values.testing }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "{{ .Values.env.name }}-certificate"
  namespace: {{ .Values.env.namespace.field }}
spec:
  isCA: true
  secretName: "{{ .Values.env.name }}-certs"
  dnsNames:
  - "{{ .Values.env.service }}"
  - "{{ .Values.env.service }}.{{ .Values.env.namespace.field }}"
  - "{{ .Values.env.service }}.{{ .Values.env.namespace.field }}.svc"
  issuerRef:
    name: "selfsigned-{{ .Values.env.name }}"
---

apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: "selfsigned-{{ .Values.env.name }}"
spec:
  selfSigned: {}
{{ end }}  