apiVersion: apps.dominodatalab.com/v1alpha1
kind: Mutation
metadata:
  name: {{ .Values.env.name }}
  namespace:  {{ .Values.env.namespace.platform }}
rules:
  - labelSelectors:
      - dominodatalab.com/workload-type in (Workspace,App,Batch,Scheduled)
      - app.kubernetes.io/managed-by != distributed-compute-operator
      {{- if .Values.users }} 
      - dominodatalab.com/starting-user-username in ({{ join "," .Values.users }})
      {{- end }}
    insertVolumeMounts:
      containerSelector:
        - run
        - jit
      volumeMounts:
        - mountPath: /etc/.aws
          name: domino-shared-store-domino-compute-vol
          subPath: domino/jit/{{ printf "{{ object['metadata']['labels']['dominodatalab.com/starting-user-id'] }}" }}
    insertContainer:
      containerType: app
      spec:
        name:  jit
        image: "{{ .Values.image.repository }}/{{ .Values.image.clientContainer }}:{{ .Values.image.clientAppVersion }}"
        imagePullPolicy: Always
    modifyEnv:
      containerSelector:
        - jit
        - run
      env:
        - name: AWS_CONFIG_FILE
          value: /etc/.aws/profile
        - name: DOMINO_JIT_ENDPOINT
          value: {{ if .Values.testing }}"http://{{ .Values.env.service }}.{{ .Values.env.namespace.field }}/jit-sessions-dummy"{{ else }}"http://{{ .Values.env.service }}.{{ .Values.env.namespace.field }}/jit-sessions"{{ end }}
        - name: DOMINO_API_PROXY
          value: http://localhost:8899
        - name: LOG_LEVEL
          value: {{ .Values.env.log_level | default "INFO" }}
  - labelSelectors:
      - dominodatalab.com/workload-type in (Workspace,App,Batch,Scheduled)
      - app.kubernetes.io/managed-by == distributed-compute-operator
      - app.kubernetes.io/component != master
      {{- if .Values.users }} 
      - dominodatalab.com/starting-user-username in ({{ join "," .Values.users }})
      {{- end }}
    insertVolumeMounts:
      volumeMounts:
        - mountPath: /etc/.aws
          name: domino-shared-store-domino-compute-vol
          subPath: domino/jit/{{ printf "{{ object['metadata']['labels']['dominodatalab.com/starting-user-id'] }}" }}
          readOnly: true   
    modifyEnv:
      env:
        - name: AWS_CONFIG_FILE
          value: /etc/.aws/profile  