apiVersion: apps.dominodatalab.com/v1alpha1
kind: Mutation
metadata:
  name: {{ .Values.env.name }}
  namespace:  {{ .Values.env.namespace.platform }}
rules:
  - labelSelectors:
      - dominodatalab.com/workload-type
      # - app.kubernetes.io/managed-by != distributed-compute-operator
      {{- if .Values.users }} 
      - dominodatalab.com/starting-user-username in ({{ join "," .Values.users }})
      {{- end }}
    insertVolumeMounts:
      containerSelector:
        - run
      volumeMounts:
        - name: log-volume
          mountPath: /var/log/jit/
          readOnly: true
        - mountPath: /etc/.aws/
          name: jit-aws-creds
          readOnly: true
    insertContainer:
      containerType: app
      spec:
        name:  jit
        image: "{{ .Values.image.repository }}/{{ .Values.image.clientContainer }}:{{ .Values.image.clientAppVersion }}"
        imagePullPolicy: Always
        volumeMounts:
          - name: log-volume
            mountPath: /var/log/jit/
          - mountPath: /etc/.aws/
            name: jit-aws-creds
    insertVolumes:
      - emptyDir: {}
        name: jit-aws-creds
      - emptyDir: {}
        name: log-volume
    modifyEnv:
      containerSelector:
        - jit
      env:
        - name: AWS_CONFIG_FILE
          value: /etc/.aws/profile
        - name: DOMINO_JIT_ENDPOINT
          value: {{ if .Values.testing }}"http://{{ .Values.env.service }}.{{ .Values.env.namespace.field }}/jit-sessions-dummy"{{ else }}"http://{{ .Values.env.service }}.{{ .Values.env.namespace.field }}/jit-sessions"{{ end }}
        - name: DOMINO_API_PROXY
          value: http://localhost:8899
        - name: LOG_LEVEL
          value: {{ .Values.env.log_level | default "INFO" }}
      containerSelector:
        - run
      env:
        - name: AWS_CONFIG_FILE
          value: /etc/.aws/profile          