apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.env.name }}
  namespace: {{ .Values.env.namespace.field }}
spec:
  ingress:
  - ports:
      - port: 8080
        protocol: TCP
      - port: 5000
        protocol: TCP
    from:
      - podSelector:
            matchLabels:
              nucleus-client: 'true'
        namespaceSelector:
            matchLabels:
              domino-compute: 'true'
  podSelector:
    matchLabels:
      app: {{ .Values.env.name }}
      {{- if .Values.testing }} 
      app: {{ .Values.env.name }}-mock
      {{- end }}      
  policyTypes:
  - Ingress
