{{- if .Values.testing }} 
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.env.name }}-mock
  namespace: {{ .Values.env.namespace.field }}
spec:
  ingress:
  - ports:
      - port: 8080
        protocol: TCP
    from:
      - podSelector:
            matchLabels:
              nucleus-client: 'true'
        namespaceSelector:
            matchLabels:
              domino-compute: 'true'
  podSelector:
    matchLabels:
      app: {{ .Values.env.name }}-mock
  policyTypes:
  - Ingress
{{- end }}