apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "{{ .Values.env.name }}"
  namespace: "{{ .Values.env.namespace.field }}"
subjects:
- kind: ServiceAccount
  name: "{{ .Values.env.name }}"
  namespace: "{{ .Values.env.namespace.field }}"
roleRef:
  kind: Role
  name: "{{ .Values.env.name }}"
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "{{ .Values.env.name }}"
  namespace: "{{ .Values.env.namespace.compute }}"
subjects:
- kind: ServiceAccount
  name: "{{ .Values.env.name }}"
  namespace: "{{ .Values.env.namespace.field }}"
roleRef:
  kind: Role
  name: "{{ .Values.env.name }}"
  apiGroup: rbac.authorization.k8s.io