{{ if .Values.testing }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.env.name }}-mock
  name: {{ .Values.env.service }}-mock
  namespace: {{ .Values.env.namespace.field }}
spec:
  ports:
  - name: http
    port: {{ .Values.mock_server.port | default 80 }}
    targetPort: {{ .Values.mock_server.containerPort | default 8080 }}
  selector:
    app: {{ .Values.env.name }}-mock
  sessionAffinity: None
  type: ClusterIP
{{ end }}