name: Docker Image CI

on:
  push:
    branches-ignore:
      - 'main'
      - 'releases-*'
    paths:
      - MockJITServerDockerfile
      - jit-mock-server/**
    tags-ignore:
      - '*'

permissions:
  contents: read
  id-token: write

jobs:
  build_push_image:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Quay
      uses: docker/login-action@v3
      with:
        logout: true        
        registry: quay.io/domino
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}
    - name: Login to Chainguard
      uses: chainguard-dev/setup-chainctl@main
      with:
        identity: ${{ secrets.CHAINGUARD_IDENTITY }}
    - name: Set up image metadata (JIT Mock API Server)
      id: docker-tags-mockapi
      uses: docker/metadata-action@v5
      with:
        images: quay.io/domino/field/jit-mock
        tags: |
          type=ref,event=branch
          type=sha
    - name: Build/Push JIT Mock API
      uses: docker/build-push-action@v5.3.0
      with:
        context: .
        file: MockJITServerDockerfile
        push: true
        tags: ${{ steps.docker-tags-mockapi.outputs.tags }}
        build-args: |
          COMMITHASH=${{ github.sha }}
          RELEASEVER=${{ github.ref_name }}          